### ISSUE TITLE
Use 'secrets' module for cryptographically secure passwords

### ISSUE THREAD

**Issue by douweschulte** [joaomcteixeira/passgen#1]
Nice project. But I would advise one change switch the use of the `random` module over to [`secrets`](https://docs.python.org/3/library/secrets.html#module-secrets). As pointed out in the documentation for the `random` module, this module is not made for cryptographic projects, the source of randomness is not good enough to prevent other people from recreating your passwords. It is better to make use of the pools of randomness provided by the operating system which can be accessed in the `secrets` module. I think the interface is sufficiently similar that a rewrite is very easy pull off.

If you want to discuss this in more detail, I would be happy to call.

**Comment by joaomcteixeira** [comment]
Hi @douweschulte  

Interesting. I didn't know about `secrets`. `passgen` is not supposed to store any values; it simply generates a key from the possible character's choice. So that you can use that password anywhere you need.

In `passgen` I do random choice of one char per type, plus random.choices for the remaining string, plus a shuffle at the end. We have more characters than `secrets.token_urlsafe`.

I can use `secrets.choice` to replace the `random.choice(s)`. Do you think it is worth orchestrating this around `secrets`?

The difference would be this one:

```python
>>> ''.join(random.choices(string.ascii_uppercase, k=16))
'LAKRTEGBXUUITEME'

>>> ''.join(secrets.choice(string.ascii_uppercase) for i in range(16))
'KDMZORPCYDKZCONC'
```

Is the first that much easier to break/guess/discover? I really don't know.

**Comment by douweschulte** [comment]
Without the use of the `secrets` it is possible to know all passwords made in a single session if one generated password from that session is known, as the random number generator is completely deterministic. Additionally depending on how the `random` is implemented there is a very big chance that an attacker has to try way less passwords because the initial seed in not sufficiently random. As is the case with most security related issues as long as a single person is using it there is a nearly zero chance of this issue being used against you, but it still is best practice to make sure it is as safe as possible. And for any future projects it is nice to know the theory.
